stages:
  stage_01:
    cmd: python stage_01.py
    deps: 
      - stage_01.py # I took stage_01.py as a dependency because I want any changes in this file to be tracked 
    outs: 
      - artifact01.txt
  stage_02:
    cmd: python stage_02.py
    deps: 
      - artifact01.txt
      - stage_02.py  
